# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choices_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 130)
        self.question_label = QtWidgets.QLabel(Form)
        self.question_label.setGeometry(QtCore.QRect(16, 20, 371, 51))
        self.question_label.setText("")
        self.question_label.setObjectName("question_label")
        self.firstChoice_pushButton = QtWidgets.QPushButton(Form)
        self.firstChoice_pushButton.setGeometry(QtCore.QRect(40, 90, 75, 23))
        self.firstChoice_pushButton.setText("")
        self.firstChoice_pushButton.setObjectName("firstChoice_pushButton")
        self.secondChoice_pushButton = QtWidgets.QPushButton(Form)
        self.secondChoice_pushButton.setGeometry(QtCore.QRect(270, 90, 75, 23))
        self.secondChoice_pushButton.setText("")
        self.secondChoice_pushButton.setObjectName("secondChoice_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
