# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compound_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(746, 495)
        self.mainTable_tableWidget = QtWidgets.QTableWidget(Form)
        self.mainTable_tableWidget.setGeometry(QtCore.QRect(10, 10, 731, 192))
        self.mainTable_tableWidget.setObjectName("mainTable_tableWidget")
        self.mainTable_tableWidget.setColumnCount(0)
        self.mainTable_tableWidget.setRowCount(0)
        self.childTables_comboBox = QtWidgets.QComboBox(Form)
        self.childTables_comboBox.setGeometry(QtCore.QRect(10, 220, 161, 22))
        self.childTables_comboBox.setObjectName("childTables_comboBox")
        self.childTable_tableWidget = QtWidgets.QTableWidget(Form)
        self.childTable_tableWidget.setGeometry(QtCore.QRect(180, 210, 561, 271))
        self.childTable_tableWidget.setObjectName("childTable_tableWidget")
        self.childTable_tableWidget.setColumnCount(0)
        self.childTable_tableWidget.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
