# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tables_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.tables_comboBox.setGeometry(QtCore.QRect(470, 40, 171, 32))
        self.tables_comboBox.setObjectName("tables_comboBox")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 451, 431))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 10, 121, 18))
        self.label.setObjectName("label")
        self.queries_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.queries_comboBox.setGeometry(QtCore.QRect(470, 110, 171, 32))
        self.queries_comboBox.setObjectName("queries_comboBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 80, 121, 18))
        self.label_2.setObjectName("label_2")
        self.visualiseTable_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.visualiseTable_pushButton.setGeometry(QtCore.QRect(470, 360, 181, 34))
        self.visualiseTable_pushButton.setObjectName("visualiseTable_pushButton")
        self.visualizeQuery_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.visualizeQuery_pushButton.setGeometry(QtCore.QRect(470, 400, 181, 34))
        self.visualizeQuery_pushButton.setObjectName("visualizeQuery_pushButton")
        self.addRecord_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addRecord_pushButton.setGeometry(QtCore.QRect(470, 150, 171, 34))
        self.addRecord_pushButton.setObjectName("addRecord_pushButton")
        self.deleteRecord_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteRecord_pushButton.setGeometry(QtCore.QRect(470, 190, 171, 34))
        self.deleteRecord_pushButton.setObjectName("deleteRecord_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Выберите таблицу:"))
        self.label_2.setText(_translate("MainWindow", "Выберите запрос:"))
        self.visualiseTable_pushButton.setText(_translate("MainWindow", "Визуализировать таблицу"))
        self.visualizeQuery_pushButton.setText(_translate("MainWindow", "Визуализировать запрос"))
        self.addRecord_pushButton.setText(_translate("MainWindow", "Добавить запись"))
        self.deleteRecord_pushButton.setText(_translate("MainWindow", "Удалить запись"))
