# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_editor_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 60, 441, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.users_listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.users_listWidget.setObjectName("users_listWidget")
        self.horizontalLayout.addWidget(self.users_listWidget)
        self.tables_listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.tables_listWidget.setObjectName("tables_listWidget")
        self.horizontalLayout.addWidget(self.tables_listWidget)
        self.allPrivileges_listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.allPrivileges_listWidget.setObjectName("allPrivileges_listWidget")
        self.horizontalLayout.addWidget(self.allPrivileges_listWidget)
        self.grantedPrivileges_listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.grantedPrivileges_listWidget.setObjectName("grantedPrivileges_listWidget")
        self.horizontalLayout.addWidget(self.grantedPrivileges_listWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addPrivilege_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addPrivilege_pushButton.setObjectName("addPrivilege_pushButton")
        self.horizontalLayout_2.addWidget(self.addPrivilege_pushButton)
        self.deletePrivilege_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deletePrivilege_pushButton.setObjectName("deletePrivilege_pushButton")
        self.horizontalLayout_2.addWidget(self.deletePrivilege_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.mainLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addPrivilege_pushButton.setText(_translate("MainWindow", "Добавить привилегию"))
        self.deletePrivilege_pushButton.setText(_translate("MainWindow", "Удалить привилегию"))
